fs=require('fs')
// fs.mkdirSync("hello")
fs.writeFileSync('hello/data.txt','Hii : ) ')
fs.appendFileSync('hello/data.txt','how is the day?')
data=fs.readFileSync('hello/data.txt','utf-8')
fs.renameSync('hello/data.txt','hello/user.txt')
console.log(data)
fs.unlinkSync('hello/user.txt')
fs.rmdirSync("hello")